
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.0
 * Query Engine version: 2ba551f319ab1df4bc874a89965d8b3641056773
 */
Prisma.prismaVersion = {
  client: "6.19.0",
  engine: "2ba551f319ab1df4bc874a89965d8b3641056773"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.EstudiantesScalarFieldEnum = {
  id: 'id',
  codigo: 'codigo',
  nombre: 'nombre',
  firstname: 'firstname',
  lastname: 'lastname',
  school_year_id: 'school_year_id',
  grado: 'grado',
  seccion: 'seccion',
  gradeId: 'gradeId',
  photo_url: 'photo_url',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.FaltasScalarFieldEnum = {
  hash: 'hash',
  id_estudiante: 'id_estudiante',
  codigo_estudiante: 'codigo_estudiante',
  tipo_falta: 'tipo_falta',
  numero_falta: 'numero_falta',
  descripcion_falta: 'descripcion_falta',
  detalle_falta: 'detalle_falta',
  acciones_reparadoras: 'acciones_reparadoras',
  autor: 'autor',
  fecha: 'fecha',
  trimestre: 'trimestre',
  nivel: 'nivel',
  attended: 'attended',
  attended_at: 'attended_at',
  observaciones: 'observaciones',
  observaciones_autor: 'observaciones_autor',
  observaciones_fecha: 'observaciones_fecha',
  created_at: 'created_at',
  updated_at: 'updated_at',
  fecha_creacion: 'fecha_creacion',
  fecha_ultima_edicion: 'fecha_ultima_edicion',
  seccion: 'seccion',
  ultimo_editor: 'ultimo_editor',
  id_externo: 'id_externo',
  school_year_id: 'school_year_id',
  trimestre_id: 'trimestre_id'
};

exports.Prisma.CasosScalarFieldEnum = {
  id_caso: 'id_caso',
  hash_falta: 'hash_falta',
  fecha_inicio: 'fecha_inicio',
  estado: 'estado'
};

exports.Prisma.SeguimientosScalarFieldEnum = {
  id_seguimiento: 'id_seguimiento',
  id_caso: 'id_caso',
  tipo_seguimiento: 'tipo_seguimiento',
  fecha_seguimiento: 'fecha_seguimiento',
  detalles: 'detalles',
  autor: 'autor',
  created_at: 'created_at',
  updated_at: 'updated_at',
  updated_by: 'updated_by'
};

exports.Prisma.AlertSettingsScalarFieldEnum = {
  id: 'id',
  seccion: 'seccion',
  primary_threshold: 'primary_threshold',
  secondary_threshold: 'secondary_threshold',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  document: 'document',
  fullName: 'fullName',
  email: 'email',
  phonenumber: 'phonenumber',
  role: 'role',
  groupCode: 'groupCode',
  gradeId: 'gradeId',
  password: 'password',
  lastLogin: 'lastLogin',
  isBlocked: 'isBlocked',
  failedLoginAttempts: 'failedLoginAttempts',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AreaPermissionsScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  areaId: 'areaId',
  canView: 'canView',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AreaScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  createdAt: 'createdAt'
};

exports.Prisma.GradeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  academicLevel: 'academicLevel',
  schoolYearId: 'schoolYearId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SyncMetadataScalarFieldEnum = {
  id: 'id',
  tabla: 'tabla',
  ultima_actualizacion: 'ultima_actualizacion',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.SyncHistoryScalarFieldEnum = {
  id: 'id',
  status: 'status',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  error: 'error',
  createdAt: 'createdAt'
};

exports.Prisma.SchoolYearScalarFieldEnum = {
  id: 'id',
  name: 'name',
  phidias_id: 'phidias_id',
  startDate: 'startDate',
  endDate: 'endDate',
  isActive: 'isActive',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TrimestreScalarFieldEnum = {
  id: 'id',
  schoolYearId: 'schoolYearId',
  name: 'name',
  order: 'order',
  startDate: 'startDate',
  endDate: 'endDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PhidiasSeguimientoScalarFieldEnum = {
  id: 'id',
  phidias_id: 'phidias_id',
  name: 'name',
  description: 'description',
  tipo_falta: 'tipo_falta',
  nivel_academico: 'nivel_academico',
  school_year_id: 'school_year_id',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PhidiasSyncLogScalarFieldEnum = {
  id: 'id',
  syncType: 'syncType',
  status: 'status',
  studentsProcessed: 'studentsProcessed',
  recordsCreated: 'recordsCreated',
  recordsUpdated: 'recordsUpdated',
  errors: 'errors',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  duration: 'duration',
  triggeredBy: 'triggeredBy'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  action: 'action',
  userId: 'userId',
  username: 'username',
  entityType: 'entityType',
  entityId: 'entityId',
  description: 'description',
  metadata: 'metadata',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  status: 'status',
  errorMessage: 'errorMessage',
  duration: 'duration',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.Role = exports.$Enums.Role = {
  ADMIN: 'ADMIN',
  ELEMENTARY_COORDINATOR: 'ELEMENTARY_COORDINATOR',
  PRESCHOOL_COORDINATOR: 'PRESCHOOL_COORDINATOR',
  MIDDLE_SCHOOL_COORDINATOR: 'MIDDLE_SCHOOL_COORDINATOR',
  HIGH_SCHOOL_COORDINATOR: 'HIGH_SCHOOL_COORDINATOR',
  PSYCHOLOGY: 'PSYCHOLOGY',
  TEACHER: 'TEACHER',
  STUDENT: 'STUDENT',
  USER: 'USER'
};

exports.Prisma.ModelName = {
  Estudiantes: 'Estudiantes',
  Faltas: 'Faltas',
  Casos: 'Casos',
  Seguimientos: 'Seguimientos',
  AlertSettings: 'AlertSettings',
  User: 'User',
  AreaPermissions: 'AreaPermissions',
  Area: 'Area',
  Grade: 'Grade',
  SyncMetadata: 'SyncMetadata',
  SyncHistory: 'SyncHistory',
  SchoolYear: 'SchoolYear',
  Trimestre: 'Trimestre',
  PhidiasSeguimiento: 'PhidiasSeguimiento',
  PhidiasSyncLog: 'PhidiasSyncLog',
  AuditLog: 'AuditLog'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
